#articles about KB collection highlights on Dutch Wikipedia
select ?item ?itemLabel ?_articleNL where {
  ?item p:P195 ?st .
  ?st ps:P195 wd:Q1526131 .
  ?st pq:P2868 wd:Q29188408 .
  OPTIONAL {
    ?_articleNL schema:about ?item.
    ?_articleNL schema:isPartOf <https://nl.wikipedia.org/>.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,nl". }
}
